# Generated by Django 5.2.7 on 2025-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('outcome', models.CharField(choices=[('WIN', 'win'), ('LOST', 'lost')], default='WIN', max_length=4, verbose_name='outcome')),
                ('pair', models.CharField(max_length=6)),
                ('profit', models.IntegerField()),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
    ]
