# Generated by Django 5.2.7 on 2025-10-08 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_journal', '0002_trade_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='image',
        ),
        migrations.CreateModel(
            name='TradePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trade_journal.trade')),
            ],
        ),
    ]
